### ISSUE TITLE
ion crashes if current working directory doesn't exist

### ISSUE THREAD

**Issue by jhasse** [redox-os/ion#413]
**Reproduction**: Run `ion` in a directory which doesn't exist. E. g. navigate to a directory with Bash, then delete it from another shell, then start ion.

**Expected behavior**: Warning or error messages

**Actual behavior**: SIGABRT

**Misc**: Linux. Backtrace:

```
thread '<unnamed>' panicked at ': "ion: failed to get current directory when building directory stack"', /checkout/src/libcore/result.rs:859
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:71
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:371
             at /checkout/src/libstd/panicking.rs:549
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   5: core::panicking::panic_fmt
             at /checkout/src/libstd/panicking.rs:471
   6: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
   7: ion::inner_main
             at /checkout/src/libcore/result.rs:761
             at .cargo/registry/src/github.com-1ecc6299db9ec823/ion-shell-1.0.4/src/shell/mod.rs:126
             at .cargo/registry/src/github.com-1ecc6299db9ec823/ion-shell-1.0.4/src/main.rs:47
```

**Comment by mmstick** [comment]
Resolved
