### ISSUE TITLE
Ion crashes when given a command `$does_not_exist`

### ISSUE THREAD

**Issue by Jatentaki** [redox-os/ion#643]
**Reproduction**: Start xfde-terminal/konsole/LXTerminal (I have only checked those), start ion by typing `ion` and then execute `$variable` where `variable` is a name of a variable which does not exist.

```bash
jatentaki@Nutria:~/Programs/raman_project$ ion
jatentaki:~/Programs/raman_project# export RUST_BACKTRACE = 1
jatentaki:~/Programs/raman_project# let exists = 1
jatentaki:~/Programs/raman_project# $exists
ion: command not found: 1
jatentaki:~/Programs/raman_project# $does_not_exist
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/jatentaki/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.4.4/lib.rs:837:18
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:69
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:397
             at /checkout/src/libstd/panicking.rs:577
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   5: core::panicking::panic_fmt
             at /checkout/src/libstd/panicking.rs:498
   6: core::panicking::panic_bounds_check
             at /checkout/src/libcore/panicking.rs:58
   7: <ion::shell::Shell as ion::shell::pipe_exec::PipelineExecution>::execute_pipeline
   8: ion::shell::Shell::run_pipeline
   9: <ion::shell::Shell as ion::shell::flow::FlowLogic>::execute_toplevel
  10: <ion::shell::Shell as ion::shell::flow::FlowLogic>::on_command
  11: <ion::shell::Shell as ion::shell::binary::Binary>::main
  12: ion::main
  13: main
  14: __libc_start_main
  15: _start
Aborted (core dumped)
```

**Expected behavior**: Likely nothing happening, like in bash.

**Actual behavior**: Ion crashes by attempting to access an empty smallvec.

**Build information**:
```bash
jatentaki@Nutria:~/Programs/raman_project$ ion --version
ion 1.0.5 (x86_64-unknown-linux-gnu)
rev 2f176ebe1010b4ebd9e2a9031ad354e598cdee9c
```

**Blocking/related**: None I know of

**Misc**: ---

**Comment by AgustinCB** [comment]
Can reproduce. Working on a fix.

**Comment by AgustinCB** [comment]
Uhm, after rebasing with master, I'm not able to reproduce anymore... Funny thing, I'm also not able to find the commit that fixed it.

Does someone else can reproduce?

**Comment by mmstick** [comment]
I can't reproduce either.

**Comment by mmstick** [comment]
My guess would be that it was the commit that I pushed which allows empty strings again.
